"""empty message

Revision ID: f171afe2db72
Revises: 218711ab8c31
Create Date: 2025-01-27 18:46:50.871523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f171afe2db72'
down_revision = '218711ab8c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr__codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_path', sa.String(length=255), nullable=False))
        batch_op.drop_column('qr_code_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr__codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_data', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('qr_code_path')

    # ### end Alembic commands ###
